//
//  Model.swift
//

import CoreData
import Combine

// Actual bookmark/folder entities will be generated by Core Data?

public protocol BookmarkStorageFactory {

    func makeReadOnlyStorage() -> BookmarkStoring

    func makeWriteableStorage() -> WritableBookmarkStoring

}

public protocol BookmarkStoring {

    var updates: AnyPublisher<Void, Never> { get }

    func fetchBookmarksInFolder(_: BookmarkEntity?) -> [BookmarkEntity]

    func fetchFavorites() -> [BookmarkEntity]

}

// Thinking ahead slightly, separate reading and writing via protocol
public protocol WritableBookmarkStoring: BookmarkStoring, Writable {

    // ... add write type functions

    func deleteBookmark(_ bookmark: BookmarkEntity)

    /// after can be nil to be at the start of the list
    func moveBookmarkInArray(_ array: [BookmarkEntity],
                             fromIndex: Int,
                             toIndex: Int) -> [BookmarkEntity]

}

public protocol Writable {

    // Not fully persisted until saved
    func save() async

}
