disabled_rules:
  - large_tuple
  - trailing_whitespace
  - trailing_comma
  - nesting

line_length:
  warning: 150
  ignores_comments: true

identifier_name:
  min_length: 1
  max_length: 1000

type_name:
  min_length: 3
  max_length:
    warning: 80
    error: 100

excluded:
  - .build
  - scripts/
