//
//  Model.swift
//

import CoreData
import Combine

// Actual bookmark/folder entities will be generated by Core Data?

public protocol BookmarkStorageFactory {

    func makeReadOnlyStorage() -> BookmarkStoring

    func makeWriteableStorage() -> WritableBookmarkStoring

}

public protocol BookmarkStoring {

    var updates: AnyPublisher<Void, Never> { get }

    func fetchBookmarksInFolder(_: Bookmark?) -> [Bookmark]

    func fetchFavorites() -> [Bookmark]

}

public protocol Bookmark {

    var parent: Bookmark? { get set }
    var title: String? { get set  }
    var url: String? { get set  }
    var isFavorite: Bool { get set  }
    var isFolder: Bool { get set }

}

// Thinking ahead slightly, separate reading and writing via protocol
public protocol WritableBookmarkStoring: BookmarkStoring, Writable {

    // ... add write type functions

    func deleteBookmark(_ bookmark: Bookmark)

    /// after can be nil to be at the start of the list
    func moveBookmark(_ bookmark: Bookmark, after: Bookmark?)

}

public protocol Writable {

    // Not fully persisted until saved
    func save() async

}
