name: Report Failed PR Checks to Asana
description: Integrates with Asana to report failed PR checks as a task.
inputs:
  asana-access-token:
    description: "Asana access token"
    required: true
    type: string
  asana-section-id:
    description: "Asana project's section ID"
    required: true
    type: string
  action:
    description: "Action to perform: choose between 'create-task' and 'close-task'"
    required: true
    type: string
  commit-author:
    description: "Last commit author's GitHub handle"
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - env:
        WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        ASANA_SECTION_ID: ${{ inputs.asana-section-id }}
        ASANA_ACCESS_TOKEN: ${{ inputs.asana-access-token }}
      shell: bash
      run: |
        case "${{ inputs.action }}" in
          "create-task")
            if [[ -n "${{ inputs.commit-author }}" ]]; then
              export ASANA_ASSIGNEE=$(jq -r .${{ inputs.commit-author }} < ${{ github.action_path }}/user_ids.json)
            fi

            ${{ github.action_path }}/report-failed-pr-checks.sh create-task \
              -t "PR Check is failing on ${{ env.GITHUB_REF_NAME }}" \
              -d "PR Checks conducted after merging have failed. See ${{ env.WORKFLOW_URL }}. Follow the steps on https://app.asana.com/0/1202500774821704/1205317064731691 to resolve this issue."
            ;;
          "close-task")
            ${{ github.action_path }}/report-failed-pr-checks.sh close-task \
              -m "Closing this one as checks are passing after a re-run. See ${{ env.WORKFLOW_URL }}/attempts/${{ github.run_attempt }} for details."
            ;;
          *)
            echo "::error::Invalid action '${{ inputs.action }}'."
            exit 1
            ;;
        esac
