name: Add PR link to Asana task

on:
  pull_request:
    types: [opened]

jobs:
  add-asana-comment:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.draft == false
        uses: aitorvs/github-asana-action@0.1.0
        with:
          asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          trigger-phrase: "Task/Issue URL:"
          action: 'add-comment'
          is-pinned: true