name: Create Pull Request

on:
  workflow_call:
    inputs:
      repo:
        description: "Repository in owner/repo format"
        required: true
        type: string
      branch:
        description: "Pull Request Branch"
        required: true
        type: string
      pr-title:
        description: "Pull Request Title"
        required: true
        type: string
      asana-task-url:
        description: "Asana Task URL"
        required: true
        type: string
    secrets:
      github-token:
        required: true
    outputs:
      url:
        description: "Pull Request URL"
        value: ${{ jobs.create-pr.outputs.url }}

jobs:
  create-pr:
    
    runs-on: ubuntu-latest

    outputs:
      url: ${{ steps.create-pr.outputs.url }}

    steps:
    - name: Create PR Body
      id: create-body
      env:
        GITHUB_TOKEN: ${{ secrets.github-token }}
      run: |
        pr_body_path=$(mktemp)
        template="$(curl $(gh api https://api.github.com/repos/${{ inputs.repo }}/contents/.github/PULL_REQUEST_TEMPLATE.md --jq .download_url))"
        sed <<< "$template" 's~\(Task.*URL:.*\)~\1 ${{ inputs.asana-task-url }}~' > "$pr_body_path"
        echo "pr_body_path=${pr_body_path}" >> $GITHUB_OUTPUT
    
    - name: Create iOS PR
      id: create-pr
      env:
        GITHUB_TOKEN: ${{ secrets.github-token }}
      run: |
        url="$(gh pr create --repo ${{ inputs.repo }} \
          --title "${{ inputs.pr-title }}" \
          --body-file "${{ steps.create-body.outputs.pr_body_path }}" \
          --assignee "${{ github.actor }}" \
          --draft \
          --head "${{ inputs.branch }}")"
        echo "url=${url}" >> $GITHUB_OUTPUT
