name: Create Platform PRs

on:
  workflow_dispatch:
    inputs:
      ios-branch:
        description: "iOS Branch"
        required: true
        type: string
      macos-branch:
        description: "macOS Branch"
        required: true
        type: string
      asana-task-url:
        description: "Asana Task URL"
        required: true
        type: string
      pr-title:
        description: "Pull Request Title"
        required: true
        type: string

jobs:
  ios-pr:
    
    name: Create iOS Pull Request
    runs-on: ubuntu-20.04

    outputs:
      url: ${{ steps.create-pr.outputs.url }}

    steps:
    - name: Create iOS PR Body
      id: create-body
      env:
        GITHUB_TOKEN: ${{ secrets.DAXMOBILE_GITHUB_TOKEN }}
      run: |
        template="$(curl $(gh api https://api.github.com/repos/duckduckgo/iOS/contents/.github/PULL_REQUEST_TEMPLATE.md --jq .download_url))"
        body="$(sed <<< "$template" 's~\(Task.*URL:.*\)~\1 ${{ github.event.inputs.asana-task-url }}~')"
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "pr_body<<$EOF" >> $GITHUB_OUTPUT
        echo "${body}" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT
    
    - name: Create iOS PR
      id: create-pr
      env:
        GITHUB_TOKEN: ${{ secrets.DAXMOBILE_GITHUB_TOKEN }}
      run: |
        pr_body_path=$(mktemp)
        echo "${{ steps.create-body.outputs.pr_body }}" > "$pr_body_path"
        url="$(gh pr create --repo duckduckgo/iOS \
          --title "${{ github.event.inputs.pr-title }}" \
          --body-file "$pr_body_path" \
          --assignee "${{ github.actor }}" \
          --draft \
          --head "${{ github.event.inputs.ios-branch }}")"
        echo "url=${url}" >> $GITHUB_OUTPUT

  macos-pr:
    
    name: Create macOS Pull Request
    runs-on: ubuntu-20.04

    outputs:
      url: ${{ steps.create-pr.outputs.url }}

    steps:
    - name: Create macOS PR Body
      id: create-body
      env:
        GITHUB_TOKEN: ${{ secrets.DAXMOBILE_GITHUB_TOKEN }}
      run: |
        template="$(curl $(gh api https://api.github.com/repos/duckduckgo/macos-browser/contents/.github/PULL_REQUEST_TEMPLATE.md --jq .download_url))"
        body="$(sed <<< "$template" 's~\(Task.*URL:.*\)~\1 ${{ github.event.inputs.asana-task-url }}~')"
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "pr_body<<$EOF" >> $GITHUB_OUTPUT
        echo "${body}" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT
    
    - name: Create macOS PR
      id: create-pr
      env:
        GITHUB_TOKEN: ${{ secrets.DAXMOBILE_GITHUB_TOKEN }}
      run: |
        pr_body_path=$(mktemp)
        echo "${{ steps.create-body.outputs.pr_body }}" > "$pr_body_path"
        url=$(gh pr create --repo duckduckgo/macos-browser \
          --title "${{ github.event.inputs.pr-title }}" \
          --body-file "$pr_body_path" \
          --assignee "${{ github.actor }}" \
          --draft \
          --head "${{ github.event.inputs.ios-branch }}")"
        echo "url=${url}" >> $GITHUB_OUTPUT

  bsk-pr:
    needs: [ios-pr, macos-pr]
    
    name: Create BSK Pull Request
    runs-on: ubuntu-20.04

    steps:
    - name: Create BSK PR Body
      id: create-body
      env:
        GITHUB_TOKEN: ${{ secrets.DAXMOBILE_GITHUB_TOKEN }}
      run: |
        template="$(curl $(gh api https://api.github.com/repos/duckduckgo/BrowserServicesKit/contents/.github/PULL_REQUEST_TEMPLATE.md --jq .download_url))"
        body="$(sed <<< "$template" \
          -e 's~\(Task.*URL:.*\)~\1${{ github.event.inputs.asana-task-url }}~' \
          -e 's~\(iOS PR:.*\)~\1${{ needs.ios-pr.outputs.url }}~' \
          -e 's~\(macOS PR:.*\)~\1${{ needs.macos-pr.outputs.url }}~')"
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "pr_body<<$EOF" >> $GITHUB_OUTPUT
        echo "${body}" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT
    
    - name: Create BSK PR
      id: create-pr
      env:
        GITHUB_TOKEN: ${{ secrets.DAXMOBILE_GITHUB_TOKEN }}
      run: |
        pr_body_path=$(mktemp)
        echo "${{ steps.create-body.outputs.pr_body }}" > "$pr_body_path"
        url="$(gh pr create --repo duckduckgo/BrowserServicesKit \
          --title "${{ github.event.inputs.pr-title }}" \
          --body-file "$pr_body_path" \
          --assignee "${{ github.actor }}" \
          --draft \
          --head "${{ github.event.inputs.ios-branch }}")"
        echo "BSK PR: ${url}\niOS PR: ${{ needs.ios-pr.outputs.url }}\nmacOS PR: ${{ needs.macos-pr.outputs.url }}" >> $GITHUB_STEP_SUMMARY
