name: SwiftLint

on:
  push:
    branches: [ main ]

jobs:
  swiftlint:

    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Run SwiftLint on all files
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --force-exclude
